import type { MouzaLayer, DataLayer } from "@/lib/types/layer"

const mouzaNames = [
  "ALI PUR_BCM",
  "ARAH_BCM",
  "ATHAL_BCM",
  "BAHDANA KALLAN_BCM",
  "BEHKAR AKKU_BCM",
  "BAIKHA FATEH BAKHSH_BCM",
  "BHANRIL KHURD_BCM",
  "BHIMBAR TRAR_BCM",
  "BHOKAR_BCM",
  "BOBRI BHEDA_BCM",
  "BOKRA_BCM",
  "BORA BANGIAL_BCM",
  "BURA BANGIAL CHAKOOK 1_BCM",
  "CHAHAAN_BCM",
  "CHAHELO_BCM",
  "CHAHNI_BCM",
  "CHAPPER MEER KHANAAL CHAKOOK_BCM",
  "CHOOCH KAAL_BCM",
  "CHUCHA_BCM",
  "DARKALA CCM_BCM",
  "DARWALA_BCM",
  "DHALAAR_BCM",
  "THLALLA_BCM",
  "DHAREK MOHRI_BCM",
  "DOHALA_BCM",
  "DORA_BCM",
  "FARASH_BCM",
  "GHANDIAN_BCM",
  "GOHRA MAST_BCM",
  "GORA SARDAR_BCM",
  "GORA SARDAR CHAKOOK 1_BCM",
  "GORA SARDAR CHAKOOK 2_BCM",
  "GRATTIAN_BCM",
  "HARNO THANDABANI_BCM",
  "HRDO GEHAR_BCM",
  "HUMAK_BCM",
  "HUN DHAMYAL_BCM",
  "JABA TAILI_BCM",
  "JABI GHAGRAN_BCM",
  "JAND GRAN_BCM",
  "JANDALA_BCM",
  "JANDALA HB 145_CHAKOOK_BCM",
  "JANG SAIDA_BCM",
  "JANGI SAIDA_BCM",
  "JHANG BAGIAL_BCM",
  "JOHAD_BCM",
  "KAJNA_BCM",
  "KAJNA CHAKOOK_BCM",
  "KANGOTA SAIDA_BCM",
  "KANGOOTA GOJJRA_BCM",
  "KARPA_BCM",
  "KARTAL BHAKRAL_BCM",
  "KHADRAIR PUR_BCM",
  "KHATRAIL_BCM",
  "KORAL_BCM",
  "KORI_BCM",
  "KOTHATHAL_BCM",
  "MAIRA BEGWAL_BCM",
  "MAJUHAN_BCM",
  "MALOT_BCM",
  "MANGIAL_BCM",
  "MEERA SUMBAL JAFFAR_BCM",
  "MERA SUMBAL AKKU_BCM",
  "MOHRIAN_BCM",
  "NARAAH SAYEDHA_BCM",
  "NIAZIAN_BCM",
  "NOON_BCM",
  "NOTHYA_BCM",
  "PAHG_BCM",
  "PAHG_CHAK_BCM",
  "PANJGRAN_BCM",
  "PANWAL_BCM",
  "PARTAAL_BCM",
  "PHULGRAN_BCM",
  "PIND BEGWAL_BCM",
  "PIND DAYA_BCM",
  "PIND MALKAAN_BCM",
  "PIND PARIAN_BCM",
  "PIND SANGRAIAL_BCM",
  "PINDORI HATHIAL_BCM",
  "PINDORI SYEDAN_BCM",
  "PONA FAQEERAN_BCM",
  "SAGA_BCM",
  "SAKNAL_BCM",
  "SANG JANI_BCM",
  "SARAI KHARBOZA_BCM",
  "SARAI MADHU_BCM",
  "SARI SARAL_BCM",
  "SHAH ALLAH DITTA_BCM",
  "SHAH PUR_BCM",
  "SHAHDARA_BCM",
  "SHEIKH PUR_BCM",
  "Sher Dhamyal_BCM",
  "SIHANA_BCM",
  "SOBUN_BCM",
  "SORAIN_BCM",
  "SYALI_BCM",
  "TARAMRI_BCM",
  "TARLAHI KHURD_BCM",
  "TARLAI KALAN_BCM",
  "TARNOL_BCM",
  "BADIA QADIR BUKSH_BCM",
  "BADIA RUSMAT KHAN_BCM",
  "BAMLA KANAT_BCM",
  "BARANADRI_BCM",
  "CHANI MASOO KHAN_BCM",
  "CHATTHA BAKHTAWAR_BCM",
  "CHIRAH_BCM",
  "DORA_BCM",
  "GAGHROTE_BCM",
  "GHANDIAN_BCM",
  "GOKINA_BCM",
  "GOLRA SHAREEF_BCM",
  "JAGIOT_BCM",
  "JANDALA_BCM",
  "KOKHA_BCM",
  "KORAK_BCM",
  "LADHOT_BCM",
  "LOHI BHAIR_BCM",
  "MADRASSA_BCM",
  "MOCHI MOHARA_BCM",
  "PAIJA_BCM",
  "RIHARA_BCM",
  "SACRELA_BCM",
  "SAHALA HB 124_BCM",
  "SAIDPUR_BCM",
  "SAIDPUR CHAKOOK_BCM",
  "SOHAN_BCM",
  "SOHDAR_BCM",
  "SUMBAL CORK_BCM",
  "TAMMA_BCM",
  "THALLAH SYEDAA_BCM",
  "THATA GUJJARAN_BCM",
  "TUMAIR_BCM",
  "GHANDIAN CHAKOOK 3_BCM",
  "GHANDIAN 2_BCM",
]

export const MOUZA_LAYERS: MouzaLayer[] = mouzaNames.map((name) => ({
  id: name.replace(/ /g, "_"),
  name: name.replace(/_/g, " ").replace(" BCM", ""),
  wmsUrl: "https://rda.ngrok.app/get_map", // Use remote WMS API
  layerName: name, // Use actual layer name for WMS param
}))

export const IMAGERY_LAYERS: MouzaLayer[] = [
  {
    id: "rawalpindimageryof2010",
    name: "Rawalpindi Imagery 2010",
    wmsUrl: "https://rda.ngrok.app/get_map",
    layerName: "rawalpindimageryof2010",
  },
  {
    id: "rawalpindiimageryof2005",
    name: "Rawalpindi Imagery 2005",
    wmsUrl: "https://rda.ngrok.app/get_map",
    layerName: "rawalpindiimageryof2005",
  },
]

export const DATA_LAYERS: DataLayer[] = [
    {
    id: 'ICT_Boundary',
    name: 'ICT Boundary',
    filePath: '/geojson/ICT_Boundary.json',
    style: { color: '#000000', weight: 3, fillOpacity: 0.0 }
  },
  {
    id: 'ICT_Zones',
    name: 'ICT Zones',
    filePath: '/geojson/ICT_Zones.json',
    style: { color: '#FF5733', weight: 2, fillOpacity: 0.3 },
    isZone: true
  },
  {
    id: 'Approved_Housing_Schemes',
    name: 'Approved Housing Schemes',
    filePath: '/geojson/Approved_Housing_Schemes.json',
    style: { color: '#28a745', weight: 2, fillOpacity: 0.3 }
  },
  {
    id: 'Illegal_Housing_Schemes',
    name: 'Illegal Housing Schemes',
    filePath: '/geojson/Illegal_Housing_Schemes.json',
    style: { color: '#ff0000', weight: 2, fillOpacity: 0.2 }
  },
  {
    id: 'LOCATION',
    name: 'Location Points',
    filePath: '/geojson/LOCATION.json',
    style: { color: '#ffcc00', weight: 1, fillOpacity: 0.9 }
  },
  {
    id: 'Railway_Line',
    name: 'Railway Line',
    filePath: '/geojson/Railway_Line.json',
    style: { color: '#000000', weight: 2, fillOpacity: 0 }
  },
  {
    id: 'Sectoral_Data',
    name: 'CDA Sector Boundary',
    filePath: '/geojson/Sectoral_Data.json',
    style: { color: '#800080', weight: 1, fillOpacity: 0.4 }
  },
  {
    id: 'Waterbodies',
    name: 'Waterbodies',
    filePath: '/geojson/Waterbodies.json',
    style: { color: '#3399ff', weight: 1, fillOpacity: 0.5 }
  },
  {
    id: 'Mouza_Boundary',
    name: 'Mouza Boundary',
    filePath: '/geojson/boundary-isb.geojson',
    style: { color: '#ff00ff', weight: 2, fillOpacity: 0.2 }
  },
]
